controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

home: 
    path: /home
    controller: App\Controller\HomeController::index

logout:
    path: /logout